export { ContentIcon } from "./ContentIcon"
export { DatabaseIcon } from "./DatabaseIcon"
export { NegativeIcon } from "./NegativeIcon"
export { PagesIcon } from "./PagesIcon"
export { PlusIcon } from "./PlusIcon"
export { PositiveIcon } from "./PositiveIcon"
export { QuestionMarkIcon } from "./QuestionMarkIcon"

export type IconName =
  | "ContentIcon"
  | "DatabaseIcon"
  | "NegativeIcon"
  | "PagesIcon"
  | "PlusIcon"
  | "PositiveIcon"
  | "QuestionMark"
