export { AstroLogo } from "./AstroLogo"
export { ContentfulLogo } from "./ContentfulLogo"
export { ContentlayerLogo } from "./ContentlayerLogo"
export { EleventyLogo } from "./EleventyLogo"
export { GatsbyLogo } from "./GatsbyLogo"
export { HugoLogo } from "./HugoLogo"
export { JekyllLogo } from "./JekyllLogo"
export { MarkdownLogo } from "./MarkdownLogo"
export { MdxLogo } from "./MdxLogo"
export { NegativeItem } from "./NegativeItem"
export { NextLogo } from "./NextLogo"
export { NotionLogo } from "./NotionLogo"
export { PositiveItem } from "./PositiveItem"
export { RemixLogo } from "./RemixLogo"
export { SanityLogo } from "./SanityLogo"
export { SvelteLogo } from "./SvelteLogo"
export { ViteLogo } from "./ViteLogo"

export type LogoName =
  | "Astro"
  | "Contentful"
  | "Contentlayer"
  | "Eleventy"
  | "Gatsby"
  | "Hugo"
  | "Jekyll"
  | "Markdown"
  | "Mdx"
  | "Next"
  | "Notion"
  | "Remix"
  | "Sanity"
  | "Svelte"
  | "Vite"
