// Icons
export { DatabaseIcon } from "./DatabaseIcon"
export { NegativeIcon } from "./NegativeIcon"
export { PagesIcon } from "./PagesIcon"
export { PositiveIcon } from "./PositiveIcon"
export { QuestionMarkIcon } from "./QuestionMarkIcon"

export type IconName =
  | "DatabaseIcon"
  | "NegativeIcon"
  | "PagesIcon"
  | "PositiveIcon"
  | "QuestionMark"

// Logos
export { AstroLogo } from "./AstroLogo"
export { ContentfulLogo } from "./ContentfulLogo"
export { ContentlayerLogo } from "./ContentlayerLogo"
export { EleventyLogo } from "./EleventyLogo"
export { GatsbyLogo } from "./GatsbyLogo"
export { HugoLogo } from "./HugoLogo"
export { JekyllLogo } from "./JekyllLogo"
export { MarkdownLogo } from "./MarkdownLogo"
export { MdxLogo } from "./MdxLogo"
export { NextLogo } from "./NextLogo"
export { NotionLogo } from "./NotionLogo"
export { RemixLogo } from "./RemixLogo"
export { SanityLogo } from "./SanityLogo"
export { SvelteLogo } from "./SvelteLogo"
export { ViteLogo } from "./ViteLogo"

export type LogoName =
  | "Astro"
  | "Contentful"
  | "Contentlayer"
  | "Eleventy"
  | "Gatsby"
  | "Hugo"
  | "Jekyll"
  | "Markdown"
  | "Mdx"
  | "Next"
  | "Notion"
  | "Remix"
  | "Sanity"
  | "Svelte"
  | "Vite"
